### ISSUE TITLE
Some graphical bugs 

### ISSUE THREAD

**Issue by cafeed28** [tsbehlman/xmb#1]
the wave always has graphic artifacts, regardless of speed, transparency, etc. that's how they look https://prnt.sc/t71gbx

**Comment by gittero11** [comment]
On my PC it's beautiful. On iOS: very distorted. On Android Chrome: wavy artifacts, tiny particles, and runs at 1 FPS.

**Comment by cafeed28** [comment]
this was a gpu issue
